name: cardamom_leaves_disease_detector
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: ^0.11.0
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_file_dialog: ^3.0.2
  image: ^4.2.0
  open_file: ^3.3.2
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.4
  shared_preferences: ^2.2.2
  permission_handler: ^12.0.1
  tflite_flutter: ^0.12.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true


  assets:
#    - assets/models/cardamom_disease_model.tflite
#    - assets/models/optimized_mobilenet.tflite
    - assets/models/mobilenet_model.tflite
    - assets/images/bg_image.png
    - assets/images/logo.png
    - assets/labels.txt
